# Generated by Django 4.2 on 2023-04-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('rasm', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('narx', models.IntegerField()),
                ('chegirma', models.IntegerField()),
                ('brened', models.CharField(max_length=30)),
                ('batafsil', models.CharField(max_length=50)),
                ('rasm', models.URLField()),
                ('holat', models.CharField(max_length=10)),
                ('mavjud', models.CharField(max_length=5)),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=60)),
                ('reyting', models.CharField(max_length=10)),
                ('sana', models.DateField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.mahsulot')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.profil')),
            ],
        ),
    ]
