# Generated by Django 4.2 on 2023-04-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
        ('Asosiy', '0002_alter_mahsulot_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='sotuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Userapp.profil'),
        ),
    ]
