# Generated by Django 4.2 on 2023-04-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
        ('Buyutmaapp', '0003_savatitem_yetkazish_puli_alter_savatitem_savat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Userapp.profil'),
        ),
    ]
