# Generated by Django 4.2 on 2023-04-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
        ('Buyutmaapp', '0004_alter_savat_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='holat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Userapp.profil'),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='sana',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='savat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Buyutmaapp.savat'),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='summa',
            field=models.IntegerField(null=True),
        ),
    ]
